# dataset infomation
dataset_name: iu_xray
image_dir: E:/Datasets/iu_xray/images/
ann_path: E:/Datasets/iu_xray/annotation.json
label_path: data/iu/r2gen_split/id_label.csv

# Hyperparameter
max_seq_length: 60
num_labels: 14
threshold: 3

batch_size: 18
epochs: 20
step_size: 50

num_layers: 3

gamma: 0.1
seed: 9223

#lr_ed: 0.0001

# Visual Extractor
# d_vf:
# efficientnet: 1280
# densenet: 1024
# resnet101: 2048

# visual_extractor: efficientnet
# pretrain_cnn_file:
# d_vf: 1280

# Output Dir
save_dir: results
